
import com.sun.awt.AWTUtilities;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Edison Andres
 */
public class RegUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegUsuario
     */
    public RegUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UsuarioText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CargoText = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        ContraseñaText = new javax.swing.JPasswordField();
        VContraseñaText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Constraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cargo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Validar Constraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        UsuarioText.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        getContentPane().add(UsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 312, -1));

        jButton1.setBackground(new java.awt.Color(128, 0, 0));
        jButton1.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        CargoText.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        CargoText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));
        CargoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoTextActionPerformed(evt);
            }
        });
        getContentPane().add(CargoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 415, 312, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrar Usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 360, 20));

        jButton2.setBackground(new java.awt.Color(128, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 50, 50));

        ContraseñaText.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        getContentPane().add(ContraseñaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 310, 30));

        VContraseñaText.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        getContentPane().add(VContraseñaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 310, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String u = UsuarioText.getText();
            String c = ContraseñaText.getText();
            String vc = VContraseñaText.getText();
            String r = (String) CargoText.getSelectedItem();
            ManejoUsuario p = new ManejoUsuario();
            Usuario a;
            a = p.consultarUsuario(u);
            if (a == null)
            {
            if (!vc.equals(c))
            {
                JOptionPane.showMessageDialog(null, "LAS CONTRASEÑAS NO SON IGUALES");
                ContraseñaText.setText(null);
                VContraseñaText.setText(null);
            }
            else{
                ManejoUsuario x = new ManejoUsuario();
                x.adicionarUsuario(u, c, r);
                JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO CORRECTAMENTE");
                UsuarioText.setText(null);
                ContraseñaText.setText(null);
                VContraseñaText.setText(null);
                }}
            else{
                JOptionPane.showMessageDialog(null, "ESTE USUARIO YA EXISTE");
                UsuarioText.setText(null);
                ContraseñaText.setText(null);
                VContraseñaText.setText(null);
            }
        } catch (IOException ex) {
            Logger.getLogger(RegUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CargoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargoTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CargoText;
    private javax.swing.JPasswordField ContraseñaText;
    private javax.swing.JTextField UsuarioText;
    private javax.swing.JPasswordField VContraseñaText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
